package com.uobia.gpes.bridge;
import java.util.List;

import com.uobia.gpes.event.Event;


public interface BehaviorTranslator {
	
	/**
	 * Behavior translators convert Events generated by the environment into a behavior (real world data or actions).
	 * They are effectively output transducers.
	 */
	
	/**
	 * Conditionally converts provided events into a behavior
	 * @param newEvents - Events generated by the environment in one step.  If events corresponding 
	 *        to the desired behavior are found then a behavior is generated.
	 *              
	 * @return true if a behavior was generated
	 */
	public boolean behave(List<Event> newEvents);
}
