package com.uobia.gpes.bridge;
import java.util.ArrayList;
import java.util.List;

import com.uobia.gpes.event.Event;


public class EventTranslator {
	//NOTE: Events may be asynchronously generated by calling generateEvents() at any time;
	private List<Event> newEvents = new ArrayList<Event>();
	
	public List<Event> getEvents() {
		generateEvents();
		List<Event> events = newEvents;
		newEvents.clear();
		return events;
	}
	
	public boolean generateEvents() {
		List<Event> events = new ArrayList<Event>();
		//Note: Implement translator here
		newEvents.addAll(events);
		return (events.size() != 0);
	}
}
