package com.uobia.gpes.bridge;
import java.util.List;

import com.uobia.gpes.event.Event;


public interface EventTranslator {

	/**
	 * Event translators convert real world data into Events for injection into an environment.
	 * They are effectively input transducers.
	 */
	
	/**
	 * Returns events generated by the translator for injection into an environment
	 * @return Events for insertion into the environment in one step
	 */
	public List<Event> getEvents();
	
	/**
	 * Generates events that can be subsequently retrieved via getEvents().
	 * This method is primarily to allow for asynchronous event generation.
	 * @return true if new events were generated
	 */
	public boolean generateEvents();
}
